---
- name: Install nginx
  apt:
    name: nginx
    state: present
  notify: "start nginx"

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: "restart nginx"
